name: Ship

on:
  pull_request:
    branches: [master]
    types:
      [
        labeled,
        unlabeled,
        edited,
        closed,
        reopened,
        synchronize,
        review_requested,
        review_request_removed,
      ]
  pull_request_review:
    types: [submitted, edited, dismissed]
  check_run:
    type: [created, rerequested, completed]
  check_suite:
    types: [completed]
  workflow_run:
    branches-ignore: [master]
    workflows: ['Node.js CI', 'CodeQL']
    types: [completed]

concurrency:
  group: |-
    ${{
      github.event.pull_request.number ||
      join(github.event.check_run.pull_requests.*.number, ', ') ||
      join(github.event.check_suite.pull_requests.*.number, ', ') ||
      join(github.event.workflow_run.pull_requests.*.number, ', ') ||
      github.sha ||
      github.ref
    }}

jobs:
  concurrency-group:
    name: Concurrency group
    runs-on: ubuntu-latest
    steps:
      - name: Concurrency group
        env:
          CONCURRENCY_GROUP: |-
            ${{
              github.event.pull_request.number ||
              join(github.event.check_run.pull_requests.*.number, ', ') ||
              join(github.event.check_suite.pull_requests.*.number, ', ') ||
              join(github.event.workflow_run.pull_requests.*.number, ', ') ||
              github.sha ||
              github.ref
            }}
        run: |
          echo "::notice::Concurrency group is $CONCURRENCY_GROUP"

  accept-to-ship:
    name: Accept to Ship
    if: |-
