name: Ship

on:
  pull_request:
    branches: [master]
    types:
      [
        labeled,
        unlabeled,
        edited,
        closed,
        reopened,
        synchronize,
        review_reques